/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication16;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author admin
 */
public class LamPhat extends javax.swing.JFrame {

    /**
     * Creates new form LamPhat
     */
    public LamPhat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        QUANTRONG = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        CHISO = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        CHISOLAMPHAT = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        DANHGIABANDAU = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        DANHGIACHUYENGIA = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        DOQUANTRONG = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        THEM = new javax.swing.JTextField();
        ADD = new javax.swing.JButton();
        MESS = new javax.swing.JLabel();
        DELETE = new javax.swing.JButton();
        UPDATE = new javax.swing.JButton();
        NHAP = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        CHISOBANDAU = new javax.swing.JLabel();
        IOWAWA1 = new javax.swing.JLabel();
        IOWAWA = new javax.swing.JLabel();
        IHOWAWA1 = new javax.swing.JLabel();
        IHOWAWA = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        OWAWA = new javax.swing.JLabel();
        HOWAWA1 = new javax.swing.JLabel();
        HOWAWA = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(204, 0, 0));

        jButton1.setForeground(new java.awt.Color(204, 0, 204));
        jButton1.setText("Introduction");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setForeground(new java.awt.Color(153, 0, 153));
        jButton2.setText("Characteristics");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jButton1)
                .addGap(95, 95, 95)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setText("Calculate inflation");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel2)
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(96, 96, 96))
        );

        jTabbedPane2.addTab(".", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("How to calculate inflation index");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("a =");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication16/tính lạm phát.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel5.setText("In which: CPI (n): Consumer value this month CPI (n-1): Consumer value last month");

        jLabel6.setText(" The IHOWAWA operator is a composite operator that uses touch and heavy sum operators in a unified framework between OWA");

        jLabel7.setText(" and weighted average. Therefore, it provides a group of aggregate controllers that are parameterized between the minimum and the total operators,");

        jLabel8.setText(" It also handles complex environments where information is assessed in order - including variables.  Its main advantage is that it can deal with ");

        jLabel9.setText("subjective information and with the complex attitude characteristics of decision makers in the same formula.");

        jLabel10.setText("These HOWA operators differ from regular OWA operators by relaxing constraints on the relevant weight vector.");

        jLabel11.setText("The HOWA operator (Yager 2002) is an operator that provides a broad class of aggregate operators, in which the sum of weights can range from 1 to infinity. ");

        jLabel12.setText("This operator has a family of parameterized aggregate operators, including the minimum, OWA, and the sum operators. . ");

        jLabel13.setText(" The heavy OWA operator (Yager 2002) is an extension of the OWA operator. This operator is useful when the available information is not limited ");

        jLabel14.setText("by the maximum or minimum operator of the regular OWA operator. ... ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(57, 57, 57))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(jLabel4))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel3))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Introduction", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setText("Inflation (negative):");

        jLabel23.setText("Negative: + Monetary loss of value measures hinders business calculations, affecting state taxes");

        jLabel24.setText(" + Redistributing income, people hoarding valuable goods suddenly increase, store hoists increase in value, money keepers get poor");

        jLabel25.setText("+ Uneven production, capital for highly profitable industries");

        jLabel26.setText(" + Do not want to keep money -> invest in buying valuable products like real estate gold and silver");

        jLabel27.setText("+ Unable to identify the trend of increasing inflation -> hindering the decision to save and invest");

        jLabel28.setText(" Solution (inflation): If inflation rises, to maintain stability, the bank must raise interest rates -> recession, unemployment");

        jLabel19.setText(" + Money increases in value -> Money kept not spent, creating habit of keeping money to harm the economy -> Stagnant demand -> Businesses ");

        jLabel21.setText(" Deflation: + Demand falls -> prices fall-> enterprise revenues fall-> not enough money for workers, wages fall-> unemployed");

        jLabel29.setText("lack of capital to invest -> increasing corporate debt-> bankruptcy");

        jLabel30.setText("\tSolution (deflation): - Increase the money supply to reduce the trend of money hoarding");

        jLabel31.setText(" - Tax reduction");

        jLabel32.setText("- Adjusted interest rates ");

        jLabel33.setText("Positive: If inflation is stable -> reducing unemployment, developed countries, the government seeks to keep inflation stable. ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel28))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25)
                            .addComponent(jLabel24))
                        .addGap(44, 44, 44))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel29))
                            .addComponent(jLabel19)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel31)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Characteristics", jPanel7);

        jButton3.setText("NEXT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 48, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(28, 28, 28))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " Inflation index", " Initial evaluation", " Evaluation of experts "
            }
        ));
        Table.setToolTipText("");
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        Table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " Inflation index", "Initial evaluation", "Additional evaluation "
            }
        ));
        jScrollPane2.setViewportView(Table2);

        QUANTRONG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "U"
            }
        ));
        jScrollPane3.setViewportView(QUANTRONG);

        jLabel15.setText(" Number of indexes");

        jLabel16.setText(" Inflation index");

        CHISOLAMPHAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHISOLAMPHATActionPerformed(evt);
            }
        });

        jLabel17.setText(" Initial evaluation");

        jLabel18.setText(" Evaluation of experts according to owawa");

        jLabel20.setText("The importance level of the target");

        jLabel34.setText(" Evaluation of experts according to Howawa");

        ADD.setText("ADD");
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });

        DELETE.setText("DELETE");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });

        UPDATE.setText("UPDATE");
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });

        NHAP.setText("ADD");
        NHAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NHAPActionPerformed(evt);
            }
        });

        jLabel35.setText(" Initial inflation indicator");

        CHISOBANDAU.setText("0");

        IOWAWA1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IOWAWA1.setText("IOWAWA");

        IOWAWA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IOWAWA.setText("0");

        IHOWAWA1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IHOWAWA1.setText("IHOWAWA");

        IHOWAWA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IHOWAWA.setText("0");

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setText("OWAWA");

        OWAWA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        OWAWA.setText("0");

        HOWAWA1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HOWAWA1.setText("HOWAWA");

        HOWAWA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HOWAWA.setText("0");

        jButton4.setText("CALCULATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel37.setForeground(new java.awt.Color(255, 51, 51));
        jLabel37.setText("Evaluate");
        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel37MouseClicked(evt);
            }
        });

        jLabel38.setForeground(new java.awt.Color(255, 0, 0));
        jLabel38.setText("Evaluate");
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });

        jLabel39.setForeground(new java.awt.Color(255, 51, 51));
        jLabel39.setText("Evaluate");
        jLabel39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel39MouseClicked(evt);
            }
        });

        jLabel40.setForeground(new java.awt.Color(204, 0, 51));
        jLabel40.setText("Evaluate");
        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel40MouseClicked(evt);
            }
        });

        jButton5.setText("Bar chart");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("SOLUTION");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("BACK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(MESS, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CHISOBANDAU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(76, 76, 76)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IOWAWA1)
                                    .addComponent(IOWAWA, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel40))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IHOWAWA1)
                                    .addComponent(IHOWAWA, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel39))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel36)
                                    .addComponent(OWAWA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel38))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HOWAWA, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel37)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton6))
                                    .addComponent(HOWAWA1)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CHISOLAMPHAT, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton5)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(DANHGIACHUYENGIA, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel17))
                                        .addGap(152, 152, 152)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CHISO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(DANHGIABANDAU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel34)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                        .addComponent(THEM, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(DOQUANTRONG, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(UPDATE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton4))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NHAP)
                                .addGap(26, 26, 26))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(ADD)
                        .addGap(91, 91, 91)
                        .addComponent(DELETE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton7)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(CHISO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(DOQUANTRONG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CHISOLAMPHAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NHAP)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(DANHGIABANDAU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel34)
                                .addComponent(THEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(DANHGIACHUYENGIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ADD)
                            .addComponent(DELETE)
                            .addComponent(UPDATE)
                            .addComponent(jButton5)
                            .addComponent(jButton4)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(MESS, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(IOWAWA1)
                    .addComponent(IHOWAWA1)
                    .addComponent(jLabel36)
                    .addComponent(HOWAWA1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OWAWA, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HOWAWA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel37)
                                .addComponent(jLabel38)
                                .addComponent(jButton6)
                                .addComponent(jLabel39))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IOWAWA, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IHOWAWA, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CHISOBANDAU))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel40)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OWAWA", "IOWAWA", "HOWAWA", "IHOWAWA"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        jLabel41.setText("0 :  Deflation");

        jLabel42.setText("1 :  Galloping Inflation");

        jLabel43.setText("2 : Inflation is stable");

        jLabel44.setText("3 :  Inflation expected");

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel45.setText(" INFLATIONARY");

        jLabel46.setText("- Implement tight monetary policy.");

        jLabel47.setText("- Strengthen price management in line with market mechanisms. ");

        jLabel48.setText(" - Concentrating efforts on developing industrial and agricultural production, quickly overcome the consequences of weather");

        jLabel49.setText(" Carry out state management of prices of a number of exclusive goods and services in accordance with the market mechanism ");

        jLabel50.setText("and principles of international economic integration by means of market supervision, cost control, apply tax.");

        jLabel52.setText(" - Restructure the economy in close association with renovating the growth model towards improving the efficiency and competitiveness of the economy.");

        jLabel54.setText(" - Creating motivation from the application of scientific and technological advances to increase product competitiveness.");

        jLabel55.setText(" - Promote the development of domestic production.");

        jLabel56.setText(" - Strengthen the analysis and forecast of the world situation, thoroughly overcome the cause of inflation due to psychological factors.");

        jLabel57.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel57.setText(" DEFLATION");

        jLabel58.setText(" - Increasing money supply to reduce the trend of saving money");

        jLabel59.setText(" - Tax reduction");

        jLabel60.setText("- Adjusted interest rates");

        jButton8.setText("BACK");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addComponent(jLabel41)
                    .addComponent(jLabel43)
                    .addComponent(jLabel44))
                .addGap(112, 112, 112))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47)
                            .addComponent(jLabel46)
                            .addComponent(jLabel48)
                            .addComponent(jLabel52)
                            .addComponent(jLabel54)
                            .addComponent(jLabel55)
                            .addComponent(jLabel56)
                            .addComponent(jLabel49)
                            .addComponent(jLabel50)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel57)
                            .addComponent(jLabel45)
                            .addComponent(jButton8)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel59)
                            .addComponent(jLabel58)
                            .addComponent(jLabel60))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel44)))
                .addGap(31, 31, 31)
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel46)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel55)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel56)
                .addGap(18, 18, 18)
                .addComponent(jLabel57)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel58)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel59)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel60)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("tab3", jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        if (Table.getSelectedRow() == -1) {
            if (Table.getRowCount() == 0) {
                MESS.setText("Table is empty");
            } else {
                MESS.setText("You must select a index");
            }
        } else {

            model.setValueAt(CHISOLAMPHAT.getText(), Table.getSelectedRow(), 0);
            model.setValueAt(DANHGIABANDAU.getText(), Table.getSelectedRow(), 1);
            model.setValueAt(DANHGIACHUYENGIA.getText(), Table.getSelectedRow(), 2);

        }
    }//GEN-LAST:event_UPDATEActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        if (Table.getSelectedRow() == -1) {
            if (Table.getRowCount() == 0) {
                MESS.setText("Table is empty");
            } else {
                MESS.setText("You must select a index");
            }
        } else {
            model.removeRow(Table.getSelectedRow());
        }
    }//GEN-LAST:event_DELETEActionPerformed

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        MESS.setText("");
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        DefaultTableModel model1 = (DefaultTableModel) Table2.getModel();

        if (!CHISOLAMPHAT.getText().trim().equals("")) {
            model.addRow(new Object[]{CHISOLAMPHAT.getText(), DANHGIABANDAU.getText(), DANHGIACHUYENGIA.getText()});
            model1.addRow(new Object[]{CHISOLAMPHAT.getText(), DANHGIABANDAU.getText(), THEM.getText()});
        } else {
            MESS.setText("ERROR");
        }
    }//GEN-LAST:event_ADDActionPerformed

    private void CHISOLAMPHATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHISOLAMPHATActionPerformed

    }//GEN-LAST:event_CHISOLAMPHATActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        DefaultTableModel model1 = (DefaultTableModel) Table2.getModel();
        CHISOLAMPHAT.setText(model.getValueAt(Table.getSelectedRow(), 0).toString());
        DANHGIABANDAU.setText(model.getValueAt(Table.getSelectedRow(), 1).toString());
        DANHGIACHUYENGIA.setText(model.getValueAt(Table.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_TableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTabbedPane2.setSelectedIndex(2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTabbedPane2.setSelectedIndex(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NHAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NHAPActionPerformed
        MESS.setText("");
        DefaultTableModel model = (DefaultTableModel) QUANTRONG.getModel();

        if (!CHISOLAMPHAT.getText().trim().equals("")) {

            model.addRow(new Object[]{DOQUANTRONG.getText()});
        } else {
            MESS.setText("ERROR");
        }
    }//GEN-LAST:event_NHAPActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (evt.getSource() == jButton4) {
            DefaultTableModel model = (DefaultTableModel) Table.getModel();
            DefaultTableModel model1 = (DefaultTableModel) Table2.getModel();
            DefaultTableModel model2 = (DefaultTableModel) QUANTRONG.getModel();
            int a = Integer.parseInt(CHISO.getText());
            float A[][] = new float[a][4];
            float B[][] = new float[a][4];
            float C[][] = new float[a][4];
            float A1[][] = new float[a][4];
            for (int i = 0; i < a; i++) {
                for (int j = 0; j < 4; j++) {
                    if (j == 3) {
                        A[i][j] = 0;
                    } else {
                        A[i][j] = Float.parseFloat(model.getValueAt(i, j).toString());
                    }
                }
            }
            float tg, k;
            int l;
            for (int i = 0; i < a - 1; i++) {
                for (int j = i + 1; j < a; j++) {
                    if (A[i][0] < A[j][0]) {
                        tg = A[i][0];
                        A[i][0] = A[j][0];
                        A[j][0] = tg;

                        k = A[i][2];
                        A[i][2] = A[j][2];
                        A[j][2] = k;
                    }
                }
            }
            for (int i = 0; i < a; i++) {
                for (int j = 0; j < 4; j++) {
                    if (j < 3) {
                        B[i][j] = 0;
                    } else {
                        B[i][j] = (float) (A[i][0] * (0.4 * A[i][1] + 0.6 * A[i][2]));
                    }
                }
            }
            for (int i = 0; i < a; i++) {
                for (int j = 0; j < 4; j++) {
                    C[i][j] = A[i][j] + B[i][j];
                }
            }
            float owawa = 0;
            for (int i = 0; i < a; i++) {

                owawa = owawa + C[i][3];

            }
            float w = 0;
            for (int i = 0; i < a; i++) {
                w = w + A[i][0] * A[i][1];
            }
            OWAWA.setText(Float.toString(owawa));
            CHISOBANDAU.setText(Float.toString(w));
            //tinh Howawa
            for (int i = 0; i < a; i++) {
                for (int j = 0; j < 4; j++) {
                    if (j == 2) {

                        A1[i][j] = Float.parseFloat(model1.getValueAt(i, j).toString());
                    } else {
                        A1[i][j] = A[i][j];
                    }
                }
            }
            for (int i = 0; i < a - 1; i++) {
                for (int j = i + 1; j < a; j++) {
                    if (A1[i][2] > A1[j][2]) {
                        k = A1[i][2];
                        A1[i][2] = A1[j][2];
                        A1[j][2] = k;
                    }
                }
            }
            for (int i = 0; i < a; i++) {
                for (int j = 0; j < 4; j++) {
                    if (j < 3) {
                        B[i][j] = 0;
                    } else {
                        B[i][j] = (float) (A1[i][0] * (0.4 * A1[i][1] + 0.6 * A1[i][2]));
                    }
                }
            }

            for (int i = 0; i < a; i++) {
                for (int j = 0; j < 4; j++) {
                    C[i][j] = A1[i][j] + B[i][j];
                }
            }
            float Howawa = 0;
            for (int i = 0; i < a; i++) {

                Howawa = Howawa + C[i][3];

            }
            HOWAWA.setText(Float.toString(Howawa));

            int[] U = new int[a];

            for (int i = 0; i < a; i++) {
                System.out.print("U[" + i + "]: ");
                U[i] = Integer.parseInt(model2.getValueAt(i, 0).toString());
            }
            for (int i = 0; i < a - 1; i++) {
                for (int j = i + 1; j < a; j++) {
                    if (U[i] < U[j]) {
                        l = U[i];
                        U[i] = U[j];
                        U[j] = l;

                        tg = A[i][0];
                        A[j][0] = A[i][0];
                        A[j][0] = tg;

                        k = A[i][1];
                        A[j][1] = A[i][1];
                        A[j][1] = k;

                    }
                }
            }
            for (int i = 0; i < a; i++) {
                for (int j = 0; j < 4; j++) {
                    if (j < 3) {
                        B[i][j] = 0;
                    } else {
                        B[i][j] = (float) (A[i][0] * (0.4 * A[i][1] + 0.6 * A[i][2]));
                    }
                }
            }
            for (int i = 0; i < a; i++) {
                for (int j = 0; j < 4; j++) {
                    C[i][j] = A[i][j] + B[i][j];
                }
            }
            float Iowawa = 0;
            for (int i = 0; i < a; i++) {

                Iowawa = Iowawa + C[i][3];

            }
            IOWAWA.setText(Float.toString(Iowawa));
            //tinh IHOWAWA
            for (int i = 0; i < a - 1; i++) {
                for (int j = i + 1; j < a; j++) {
                    if (U[i] < U[j]) {
                        l = U[i];
                        U[i] = U[j];
                        U[j] = l;

                        tg = A1[i][0];
                        A1[j][0] = A1[i][0];
                        A1[j][0] = tg;

                        k = A1[i][1];
                        A1[j][1] = A1[i][1];
                        A1[j][1] = k;

                    }
                }
            }

            for (int i = 0; i < a; i++) {
                for (int j = 0; j < 4; j++) {
                    if (j < 3) {
                        B[i][j] = 0;
                    } else {
                        B[i][j] = (float) (A1[i][0] * (0.4 * A1[i][1] + 0.6 * A1[i][2]));
                    }
                }
            }
            for (int i = 0; i < a; i++) {
                for (int j = 0; j < 4; j++) {
                    C[i][j] = A1[i][j] + B[i][j];
                }
            }
            float IHowawa = 0;
            for (int i = 0; i < a; i++) {

                IHowawa = IHowawa + C[i][3];

            }
            IHOWAWA.setText(Float.toString(IHowawa));
            float g = Float.parseFloat(HOWAWA.getText());
            float b = Float.parseFloat(OWAWA.getText());
            float c = Float.parseFloat(IOWAWA.getText());
            float d = Float.parseFloat(IHOWAWA.getText());
            float e = Float.parseFloat(CHISOBANDAU.getText());
            float f = g - e;
            float f1 = b - e;
            float f2 = c - e;
            float f3 = d - e;
            int p, y, u, o;

            if (f > 0) {
                if (f > 0.1) {
                    p = 1;
                } else {
                    if (0.02 <= f && f <= 0.05) {
                        p = 2;
                    } else {
                        p = 3;
                    }
                }
            } else {
                p = 0;
            }

            if (f1 > 0) {
                if (f1 > 0.1) {
                    y = 1;
                } else {
                    if (0.02 <= f1 && f1 <= 0.05) {
                        y = 2;
                    } else {
                        y = 3;
                    }
                }
            } else {
                y = 0;
            }

            if (f2 > 0) {
                if (f2 > 0.1) {
                    u = 1;
                } else {
                    if (0.02 <= f2 && f2 <= 0.05) {
                        u = 2;
                    } else {
                        u = 3;
                    }
                }
            } else {
                u = 0;
            }

            if (f3 > 0) {
                if (f3 > 0.1) {
                    o = 1;
                } else {
                    if (0.02 <= f3 && f3 <= 0.05) {
                        o = 2;
                    } else {
                        o = 3;
                    }
                }
            } else {
                o = 0;
            }
            DefaultTableModel model3 = (DefaultTableModel) jTable1.getModel();
            model3.addRow(new Object[]{y, u, p, o});
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseClicked
        float a = Float.parseFloat(HOWAWA.getText());
        float b = Float.parseFloat(CHISOBANDAU.getText());
        float c = a - b;

        if (c > 0) {
            if (c > 0.1) {
                JOptionPane.showMessageDialog(this, "The results show that there is galloping inflation (unexpected case).");
            } else {
                if (0.02 <= c && c <= 0.05) {
                    JOptionPane.showMessageDialog(this, "The results show that inflation is stable");
                } else {
                    JOptionPane.showMessageDialog(this, "The results show that inflation is expected");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "The results show that deflation");
        }
    }//GEN-LAST:event_jLabel37MouseClicked

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        float a = Float.parseFloat(OWAWA.getText());
        float b = Float.parseFloat(CHISOBANDAU.getText());
        float c = a - b;

        if (c > 0) {
            if (c > 0.1) {
                JOptionPane.showMessageDialog(this, "The results show that there is galloping inflation (unexpected case).");
            } else {
                if (0.02 <= c && c <= 0.05) {
                    JOptionPane.showMessageDialog(this, "The results show that inflation is stable");
                } else {
                    JOptionPane.showMessageDialog(this, "The results show that inflation is expected");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "The results show that deflation");
        }
    }//GEN-LAST:event_jLabel38MouseClicked

    private void jLabel39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel39MouseClicked
        float a = Float.parseFloat(IHOWAWA.getText());
        float b = Float.parseFloat(CHISOBANDAU.getText());
        float c = a - b;

        if (c > 0) {
            if (c > 0.1) {
                JOptionPane.showMessageDialog(this, "The results show that there is galloping inflation (unexpected case).");
            } else {
                if (0.02 <= c && c <= 0.05) {
                    JOptionPane.showMessageDialog(this, "The results show that inflation is stable");
                } else {
                    JOptionPane.showMessageDialog(this, "The results show that inflation is expected");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "The results show that deflation");
        }
    }//GEN-LAST:event_jLabel39MouseClicked

    private void jLabel40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseClicked
        float a = Float.parseFloat(IOWAWA.getText());
        float b = Float.parseFloat(CHISOBANDAU.getText());
        float c = a - b;

        if (c > 0) {
            if (c > 0.1) {
                JOptionPane.showMessageDialog(this, "The results show that there is galloping inflation (unexpected case).");
            } else {
                if (0.02 <= c && c <= 0.05) {
                    JOptionPane.showMessageDialog(this, "The results show that inflation is stable");
                } else {
                    JOptionPane.showMessageDialog(this, "The results show that inflation is expected");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "The results show that deflation");
        }
    }//GEN-LAST:event_jLabel40MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        float a = Float.parseFloat(HOWAWA.getText());
        float b = Float.parseFloat(OWAWA.getText());
        float c = Float.parseFloat(IOWAWA.getText());
        float d = Float.parseFloat(IHOWAWA.getText());
        float e = Float.parseFloat(CHISOBANDAU.getText());
        float f = a - e;
        float f1 = b - e;
        float f2 = c - e;
        float f3 = d - e;
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(f, "", "HOWAWA");
        dataset.setValue(f1, "", "OWAWA");
        dataset.setValue(f2, "", "IOWAWA");
        dataset.setValue(f3, "", "IHOWAWA");
        JFreeChart chart = ChartFactory.createBarChart("Inflation Chart", "The expression identifies", "Inflation value", dataset, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot p = chart.getCategoryPlot();

        ChartFrame frame = new ChartFrame("Bar chart for inflationary", chart);
        frame.setVisible(true);
        frame.setSize(450, 350);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LamPhat.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LamPhat.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LamPhat.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LamPhat.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LamPhat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JTextField CHISO;
    private javax.swing.JLabel CHISOBANDAU;
    private javax.swing.JTextField CHISOLAMPHAT;
    private javax.swing.JTextField DANHGIABANDAU;
    private javax.swing.JTextField DANHGIACHUYENGIA;
    private javax.swing.JButton DELETE;
    private javax.swing.JTextField DOQUANTRONG;
    private javax.swing.JLabel HOWAWA;
    private javax.swing.JLabel HOWAWA1;
    private javax.swing.JLabel IHOWAWA;
    private javax.swing.JLabel IHOWAWA1;
    private javax.swing.JLabel IOWAWA;
    private javax.swing.JLabel IOWAWA1;
    private javax.swing.JLabel MESS;
    private javax.swing.JButton NHAP;
    private javax.swing.JLabel OWAWA;
    private javax.swing.JTable QUANTRONG;
    private javax.swing.JTextField THEM;
    private javax.swing.JTable Table;
    private javax.swing.JTable Table2;
    private javax.swing.JButton UPDATE;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
